INSERT INTO relationtype(id, partner, relationtype) VALUES(1, true, 'Is gehuwd met');
INSERT INTO relationtype(id, partner, relationtype) VALUES(2, true, 'Is partner van');
INSERT INTO relationtype(id, partner, relationtype) VALUES(3, false, 'Is kind van');
INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1001, 'Groot'             , 'Egbert Johannes'              , ''     , '1803-05-08' , 'Juist'        , 'man'   , 0     , ''        , ''         , '1877-06-12'    , '12345678', ''          , ''      , 'Egbert' , ''   , ''                      , ''          , 'de'     );
INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1002, 'Pieters'           , 'Aaltje'                       , ''     , '1800-03-16' , 'Hoorn'        , 'vrouw' , 0     , ''        , ''         , '1865-07-22'    , '12345678', ''          , ''      , 'Aaltje' , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10000, true, 'Is gehuwd met', 1001, 1002);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10001, true, 'Is gehuwd met', 1002, 1001);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1003, 'Groot'             , 'Egberdina Alida'              , ''     , '1835-04-08' , 'Terschelling' , 'vrouw' , 0     , ''        , ''         , '1898-12-23'    , '12345678', ''          , ''      , 'Egberdina' , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10002, false, 'Is kind van', 1003, 1001);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10003, false, 'Is kind van', 1003, 1002);
INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1004, 'Sijmons'           , 'Franciscus Antonius'          , ''     , '1839-10-09' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1911-07-24'    , '12345678', ''          , ''      , 'Frans'     , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10004, true, 'Is gehuwd met', 1003, 1004);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10005, true, 'Is gehuwd met', 1004, 1003);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1007, 'Sijmons'           , 'Anna Maria'                   , ''     , '1860-12-22' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1935-04-05'    , '12345678', ''          , ''      , 'Anna'      , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10010, false, 'Is kind van', 1007, 1003);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10011, false, 'Is kind van', 1007, 1004);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1008, 'Sijmons'           , 'Alida'                        , ''     , '1863-02-11' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1927-04-08'    , '12345678', ''          , ''      , 'Alida'     , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10012, false, 'Is kind van', 1008, 1003);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10013, false, 'Is kind van', 1008, 1004);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1009, 'Sijmons'           , 'Franciscus Antonius'          , ''     , '1865-06-14' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1937-06-13'    , '12345678', ''          , ''      , 'Frans'     , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10014, false, 'Is kind van', 1009, 1003);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10015, false, 'Is kind van', 1009, 1004);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1010, 'Sijmons'           , 'Egbert Johannes'              , ''     , '1868-03-10' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1945-05-07'    , '12345678', ''          , ''      , 'Egbert'    , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10016, false, 'Is kind van', 1010, 1003);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10017, false, 'Is kind van', 1010, 1004);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1011, 'Sijmons'           , 'Barend'                       , ''     , '1870-07-31' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1871-10-29'    , '12345678', ''          , ''      , 'Barend'    , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10018, false, 'Is kind van', 1011, 1003);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10019, false, 'Is kind van', 1011, 1004);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1012, 'Sijmons'           , 'Barend'                       , ''     , '1872-07-26' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1928-10-21'    , '12345678', ''          , ''      , 'Barend'    , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10020, false, 'Is kind van', 1012, 1003);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10021, false, 'Is kind van', 1012, 1004);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1005, 'Groot'             , 'Berend'                       , ''     , '1840-01-06' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1917-04-30'    , '12345678', ''          , ''      , 'Bernd'     , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10006, false, 'Is kind van', 1005, 1001);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10007, false, 'Is kind van', 1005, 1002);
INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1006, 'Grondman', 'Carolina Johanna Wilhelmina', ''     , '1840-03-03' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1920-11-08'    , '12345678', ''          , ''      , 'Lien'      , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10008, true, 'Is gehuwd met', 1005, 1006);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10009, true, 'Is gehuwd met', 1006, 1005);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1013, 'Groot'             , 'Egbert Johannes'              , ''     , '1864-03-03' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1928-10-21'    , '12345678', ''          , ''      , 'Egbert'    , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10022, false, 'Is kind van', 1013, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10023, false, 'Is kind van', 1013, 1006);
INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1020, 'Rademann', 'Sjoerderika Clasina'        , ''     , '1862-06-24' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1942-06-13'    , '12345678', ''          , ''      , 'Sjoerderika' , ''   , ''                      , ''          , ''     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10036, true, 'Is gehuwd met', 1020, 1013);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10037, true, 'Is gehuwd met', 1013, 1020);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1021, 'Groot'             , 'Egbert Johannes'              , ''     , '1899-04-24' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1928-10-21'    , '12345678', ''          , ''      , 'Broer'     , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10038, false, 'Is kind van', 1021, 1013);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10039, false, 'Is kind van', 1021, 1020);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1022, 'Groot'             , 'Wilhelmina Johanna Clasina'   , ''     , '1907-04-08' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1933-06-28'    , '12345678', ''          , ''      , 'Willy'     , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10040, false, 'Is kind van', 1022, 1013);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10041, false, 'Is kind van', 1022, 1020);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1014, 'Groot'             , 'Barend'                       , ''     , '1866-11-04' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1928-10-21'    , '12345678', ''          , ''      , 'Barend'    , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10024, false, 'Is kind van', 1014, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10025, false, 'Is kind van', 1014, 1006);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1015, 'Groot'             , 'Carolina Johannna Wilhelmina' , ''     , '1869-01-12' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1945-12-31'    , '12345678', ''          , ''      , 'Lien'      , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10026, false, 'Is kind van', 1015, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10027, false, 'Is kind van', 1015, 1006);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1016, 'Groot'             , 'Franciscus Antonius'          , ''     , '1872-02-07' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1945-12-31'    , '12345678', ''          , ''      , 'Frans'     , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10028, false, 'Is kind van', 1016, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10029, false, 'Is kind van', 1016, 1006);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1017, 'Groot'             , 'Carel Willem'                 , ''     , '1874-10-18' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1945-12-31'    , '12345678', ''          , ''      , 'Carel'     , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10030, false, 'Is kind van', 1017, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10031, false, 'Is kind van', 1017, 1006);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1018, 'Groot'             , 'Egberdina Alida'              , ''     , '1876-12-03' , 'Amsterdam'    , 'vrouw' , 0     , ''        , ''         , '1877-05-21'    , '12345678', ''          , ''      , 'Egberdina' , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10032, false, 'Is kind van', 1018, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10033, false, 'Is kind van', 1018, 1006);

INSERT INTO person(id  , achternaam          , doopnaam                       , email  , geboortedatum, geboorteplaats , geslacht, huisnr, huisnrtoev, land       , overlijdensdatum, password  , plaatsnaam  , postcode, roepnaam    , staat, straatnaam              , telefoon    , tussenvoegsel) VALUES (1019, 'Groot'             , 'Johannes Barend'              , ''     , '1878-06-22' , 'Amsterdam'    , 'man'   , 0     , ''        , ''         , '1877-05-21'    , '12345678', ''          , ''      , 'Jan'       , ''   , ''                      , ''          , 'de'     );
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10034, false, 'Is kind van', 1019, 1005);
INSERT INTO relation(id, partner, relatietype, person1_id, person2_id) VALUES(10035, false, 'Is kind van', 1019, 1006);
